name: compressTinypngImage
version: 1.0.0
description: >-
  Compress image using tinypng api
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  dart_appwrite: ^1.0.1
  http: ^0.13.4

dev_dependencies:
  test: '>=1.15.0 <2.0.0'